### PR TITLE
remove k8s_version definition

### PR DESCRIPTION
**Pull request by Andrey-mp**
ansible-deployer has own k8s_version definition that is supported

### CODE REVIEW

**Comment by swill** [comment]
Can you reference here in a comment how the K8s version is specified via the ansible deployer so it is documented with this change?  Thanks...

**Comment by Andrey-mp** [comment]
@swill k8s version can be passed like all other parameters in instances.yaml like it was here https://github.com/tungstenfabric/tf-devstack/pull/1/files#diff-7b4368afeff1107529b8fba6196f6e8a
but it's not good to pin any version in devstack - ansible-deployer has own default version that was bumped some time ago.

**Comment by swill** [comment]
Ahh, ok. Makes sense. Thanks...

**Comment by swill** [comment]
LGTM :+1:

**Comment by swill** [comment]
@Andrey-mp can you please reopen this PR against the official source repo: https://gerrit.tungsten.io/r/admin/repos/tungstenfabric/tf-devstack

If you have any issue submitting the PR there, please review the instructions in this Jira ticket for details: https://jira.tungsten.io/browse/TFB-1449

We will not be merging the PR in GH because it is simply a mirror of the gerrit repo.  We will be closing this PR here once you create the PR in gerrit.  Thanks for your contribution...

**Pull request closed without merging**
